alias gri='git rebase -i'
alias griom='gri origin/master'
alias griod='gri origin/develop'
alias grium='gri upstream/master'
alias griud='gri upstream/develop'
alias grc='git rebase --continue'
alias grh='git reset --hard'
